### ISSUE TITLE
CANNOT LINK EXECUTABLE: cannot locate symbol "in6addr_any" referenced by "./iperf3.9"

### ISSUE THREAD

**Issue by tosiara** [KnightWhoSayNi/android-iperf#6]
Android 5.1.1 LineageOS
Kernel 3.10.9 armv7l 

When running `./iperf3.9` an error shown:

```
$ ./iperf3.9
WARNING: linker: ./iperf3.9: unused DT entry: type 0x6ffffffe arg 0x11dc
WARNING: linker: ./iperf3.9: unused DT entry: type 0x6fffffff arg 0x3
CANNOT LINK EXECUTABLE: cannot locate symbol "in6addr_any" referenced by "./iperf3.9"...
```

**Comment by KnightWhoSayNi** [comment]
Binaries were built against Android `9.0` with NDK `r19`.

They are not supported by older Android versions. Either upgrade your device or compile it by yourself using provided _Dockerfile_.

Please follow _Download_ section for more details.

> Compiled iperf and iperf3 binaries using SDK 4333796 and NDK r19 for devices with Android 9.0+ (API level 28+)
