### ISSUE TITLE
Cannot run program "/data/user/0/com.mhmm.iperf/files/iperf3": error=13, Permission denied

### ISSUE THREAD

**Issue by mhmm2005** [KnightWhoSayNi/android-iperf#9]
I used one of compiled binary file iperf3.9 and try to execute a command but it gaves permission denied all the time. i set the file also to executive. public static String runIperfCommand(String command) {
        StringBuilder output = new StringBuilder();

        try {
            Process process = Runtime.getRuntime().exec(command);
            InputStream inputStream = process.getInputStream();
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));

            String line;
            while ((line = reader.readLine()) != null) {
                output.append(line).append("\n");
            }

            process.waitFor();
        } catch (IOException | InterruptedException e) {
            Log.e("TAG123", "runIperfCommand: "+ e.getMessage() );
        }

        return output.toString();
    }

 Process process = new ProcessBuilder("chmod", "777", context.getFilesDir() + "/" + file.getName()).redirectErrorStream(true).start();
                        // Log the output of the chmod command
                        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
                        String line;
                        while ((line = reader.readLine()) != null) {
                            Log.d("TAG123", "chmod output: " + line);
                        }

                        int exitCode = process.waitFor();
                        if (exitCode == 0) {
                            // File is now executable
                            Log.i("TAG123", "copyAssetFileToInternalStorage: is executable");
                        } else {
                            // Handle the error
                            Log.e("TAG123", "copyAssetFileToInternalStorage: error");
                        }

**Comment by KnightWhoSayNi** [comment]
This is not the scope of this project. As mentioned in [README](README.md), provided pre-compiled binaries can be executed only from `/data/local/tmp`.

Either root your device or bundle binaries with your Android app.
